CREATE ROLE IF NOT EXISTS OPENTOFU_ROLE;
CREATE USER OPENTOFU_USER 
RSA_PUBLIC_KEY='
-----BEGIN PUBLIC KEY-----
...
-----END PUBLIC KEY-----
'
DEFAULT_ROLE = OPENTOFU_ROLE 
MUST_CHANGE_PASSWORD = FALSE
;
GRANT ROLE OPENTOFU_ROLE TO USER OPENTOFU_USER;

GRANT CREATE DATABASE ON ACCOUNT TO ROLE OPENTOFU_ROLE;
GRANT CREATE ROLE ON ACCOUNT TO ROLE OPENTOFU_ROLE;
GRANT USAGE ON WAREHOUSE PROD_WH TO ROLE OPENTOFU_ROLE;
GRANT MONITOR USAGE ON ACCOUNT TO ROLE OPENTOFU_ROLE;
GRANT MANAGE GRANTS ON ACCOUNT TO ROLE OPENTOFU_ROLE;